services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - ${WEB_PORT:-3000}:5173
    environment:
      PORT: ${WEB_PORT:-3000}
    volumes:
      - ./frontend:/app
    depends_on:
      - mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - ${API_PORT:-8004}:8000
    volumes:
      - ./backend:/home
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0.5
    ports:
      - 27018:27017
    environment:
      # Use root/example as user/password credentials
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
      TZ: Asia/Tokyo
